/** Static mock data for Manage Data page */

export const productInventory = [
  {
    id: "p1",
    name: "Amul Taza Milk (500ml)",
    category: "Dairy",
    quantity: 12,
    branch: "Rajpura",
    expiryDate: "2026-04-11",
    status: "expiring",
    price: 25,
  },
  {
    id: "p2",
    name: "Britannia Bread",
    category: "Bakery",
    quantity: 8,
    branch: "Rajpura",
    expiryDate: "2026-04-10",
    status: "expiring",
    price: 40,
  },
  {
    id: "p3",
    name: "Tata Salt (1kg)",
    category: "Groceries",
    quantity: 45,
    branch: "Chandigarh",
    expiryDate: "2027-06-15",
    status: "healthy",
    price: 28,
  },
  {
    id: "p4",
    name: "Maggi Noodles (Pack of 12)",
    category: "Snacks",
    quantity: 5,
    branch: "Pinjore",
    expiryDate: "2026-12-22",
    status: "low-stock",
    price: 144,
  },
  {
    id: "p5",
    name: "Coca-Cola (2L)",
    category: "Cold drinks",
    quantity: 3,
    branch: "Rajpura",
    expiryDate: "2026-08-30",
    status: "low-stock",
    price: 90,
  },
  {
    id: "p6",
    name: "Parle-G Biscuits (800g)",
    category: "Snacks",
    quantity: 60,
    branch: "Chandigarh",
    expiryDate: "2026-11-15",
    status: "healthy",
    price: 75,
  },
  {
    id: "p7",
    name: "Dettol Soap (Pack of 3)",
    category: "Groceries",
    quantity: 22,
    branch: "Pinjore",
    expiryDate: "2028-03-01",
    status: "healthy",
    price: 165,
  },
  {
    id: "p8",
    name: "Haldiram Namkeen (400g)",
    category: "Snacks",
    quantity: 4,
    branch: "Rajpura",
    expiryDate: "2026-04-12",
    status: "expiring",
    price: 120,
  },
  {
    id: "p9",
    name: "Dabur Real Juice (1L)",
    category: "Cold drinks",
    quantity: 6,
    branch: "Chandigarh",
    expiryDate: "2026-04-15",
    status: "expiring",
    price: 110,
  },
  {
    id: "p10",
    name: "Aashirvaad Atta (5kg)",
    category: "Groceries",
    quantity: 30,
    branch: "Pinjore",
    expiryDate: "2026-09-20",
    status: "healthy",
    price: 295,
  },
  {
    id: "p11",
    name: "Mother Dairy Curd (400g)",
    category: "Dairy",
    quantity: 2,
    branch: "Rajpura",
    expiryDate: "2026-04-10",
    status: "expiring",
    price: 35,
  },
  {
    id: "p12",
    name: "Surf Excel (1kg)",
    category: "Groceries",
    quantity: 18,
    branch: "Chandigarh",
    expiryDate: "2027-05-01",
    status: "healthy",
    price: 230,
  },
];

export const BRANCH_OPTIONS = ["All Branches", "Rajpura", "Chandigarh", "Pinjore"];

export const STOCK_FILTERS = ["All", "Low Stock", "Expiring Soon", "Healthy"];

export const CATEGORY_FILTERS = ["All", "Dairy", "Bakery", "Groceries", "Snacks", "Cold drinks"];

export const aiChatMessages = [
  {
    id: "m1",
    role: "assistant",
    text: "👋 Hi! I'm your BharatPulse AI assistant. Ask me anything about your inventory, stock alerts, or business insights.",
  },
  {
    id: "m2",
    role: "user",
    text: "Which products are about to expire?",
  },
  {
    id: "m3",
    role: "assistant",
    text: "🚨 **5 products expiring within the next week:**\n\n• **Amul Taza Milk** — expires in 2 days (Rajpura, 12 units)\n• **Britannia Bread** — expires tomorrow (Rajpura, 8 units)\n• **Mother Dairy Curd** — expires tomorrow (Rajpura, 2 units)\n• **Haldiram Namkeen** — expires in 3 days (Rajpura, 4 units)\n• **Dabur Real Juice** — expires in 6 days (Chandigarh, 6 units)\n\n💡 *Recommendation: Run a Buy-1-Get-1 offer on these items to reduce waste.*",
  },
  {
    id: "m4",
    role: "user",
    text: "Which branch has low stock?",
  },
  {
    id: "m5",
    role: "assistant",
    text: "📊 **Stock alerts by branch:**\n\n**Rajpura** — Most critical\n• Coca-Cola (2L): Only 3 units left\n• Mother Dairy Curd: Only 2 units left\n\n**Pinjore**\n• Maggi Noodles: Only 5 packs remaining\n\n**Chandigarh** — All stocks healthy ✅\n\n💡 *Suggestion: Transfer surplus from Chandigarh to Rajpura for Cold drinks before the heatwave.*",
  },
  {
    id: "m6",
    role: "user",
    text: "What should I restock?",
  },
  {
    id: "m7",
    role: "assistant",
    text: "📦 **Recommended restock list (priority order):**\n\n1. **Coca-Cola (2L)** — Low stock + heatwave approaching → Order 24+ units for Rajpura\n2. **Maggi Noodles** — school season demand spike expected → Order 20 packs for Pinjore\n3. **Mother Dairy Curd** — Daily essential, very low → Order 15 units for Rajpura\n4. **Dairy products** — Wedding season in your area → stock 40% extra\n\n📈 *Based on your last 3 months' sales trend and weather forecast.*",
  },
];
