const mongoose = require("mongoose");

/**
 * Alert — generated by the rule-based alert engine.
 *
 * Each alert is linked to one InventoryItem and carries a type + severity.
 * Alerts are upserted (one active alert per item+type) so duplicate runs
 * don't flood the collection.
 */
const AlertSchema = new mongoose.Schema(
  {
    // Reference to the affected inventory item
    inventoryItemId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "InventoryItem",
      required: true,
      index: true,
    },
    productId:   { type: String, required: true, index: true },
    productName: { type: String, required: true },

    // ── Alert classification ──────────────────────────────────────────────────
    type: {
      type: String,
      enum: ["low_stock", "out_of_stock", "expiring_soon", "overstock"],
      required: true,
    },
    severity: {
      type: String,
      enum: ["info", "warning", "critical"],
      required: true,
    },
    message: { type: String, required: true },

    // Snapshot values at time of alert
    quantityAtAlert: { type: Number, default: null },
    expiryDateAtAlert: { type: Date, default: null },

    // Lifecycle
    resolved: { type: Boolean, default: false, index: true },
    resolvedAt: { type: Date, default: null },
  },
  {
    timestamps: true,
    collection: "alerts",
  }
);

// Compound index for the upsert key (one active alert per item+type)
AlertSchema.index({ inventoryItemId: 1, type: 1, resolved: 1 });

module.exports = mongoose.model("Alert", AlertSchema);
