const mongoose = require("mongoose");

/**
 * Recommendation — AI-generated suggestion for a specific inventory item.
 *
 * Generated by the Groq-backed AI engine. Each run replaces the previous
 * recommendation for that item (upsert by inventoryItemId).
 */
const RecommendationSchema = new mongoose.Schema(
  {
    // Reference to the inventory item this recommendation is for
    inventoryItemId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "InventoryItem",
      required: true,
      // NOTE: unique index defined below via schema.index() — don't set index:true here
    },
    productId:   { type: String, required: true, index: true },
    productName: { type: String, required: true },

    // ── AI output ─────────────────────────────────────────────────────────────
    type: {
      type: String,
      enum: ["restock", "discount", "demand_insight", "hold", "other"],
      required: true,
    },
    suggestion: { type: String, required: true },   // Human-readable action
    reasoning:  { type: String, default: null },    // AI's reasoning
    priority:   {
      type: String,
      enum: ["low", "medium", "high", "urgent"],
      default: "medium",
    },
    confidence: { type: Number, min: 0, max: 1, default: null }, // 0–1 score

    // ── Inventory snapshot ────────────────────────────────────────────────────
    // Stored so we can audit what data drove the recommendation
    inventorySnapshot: { type: mongoose.Schema.Types.Mixed, default: {} },

    // Raw response from the AI (for debugging / auditing)
    rawAIResponse: { type: String, default: null },

    generatedAt: { type: Date, default: Date.now },
  },
  {
    timestamps: true,
    collection: "recommendations",
  }
);

// One recommendation per item (latest wins via upsert)
RecommendationSchema.index({ inventoryItemId: 1 }, { unique: true });

module.exports = mongoose.model("Recommendation", RecommendationSchema);
